backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images" 
public_folder: "/images" 

collections:
  - name: "nft" # Used in routes, e.g., /admin/collections/blog
    label: "NFT" # Used in the UI
    folder: "nft" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Collection", name: "collection", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Collection", name: "collection", widget: "relation", collection: "collections", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false}
      - name: items
        widget: list
        types:
          - name: item_section
            label: Add Item
            widget: object
            fields: 
              - {name: name, widget: string}
              - {name: image, widget: image}
              - {name: price, widget: string}
              - {name: content, widget: markdown}
              - {name: date, widget: datetime}