backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images" 
public_folder: "/images" 

collections:
  - name: "nft" # Used in routes, e.g., /admin/collections/blog
    label: "NFT" # Used in the UI
    folder: "collection" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Collection", name: "collection", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Price", name: "price", widget: "string"}
      - name: sections
        widget: list
        types:
          - name: text_section
            label: Text
            widget: object
            fields: 
              - {name: text, widget: markdown}

          - name: image_section
            label: Image
            widget: object
            fields: 
              - {name: image, widget: image}
              - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}


          - name: slider_section
            label: Slider
            widget: object
            fields:
              - name: images  
                widget: list
                field: {label: Image, name: image, widget: image}
              - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}